apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: ensino
  labels:
    app: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1.13.11
          name: pi60808-proj1-nginx
          livenessProbe:
            httpGet:
              path: /status
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 1
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: nginx-nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      restartPolicy: Always
      volumes:
      - name: nginx-nginx-conf
        configMap:
          name: nginx-nginx-conf
