apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-http
  namespace: ensino
spec:
  externalIPs:
    - "191.36.8.21"
    - "191.36.8.22"
    - "191.36.8.23"
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
