apiVersion: v1
kind: PersistentVolume
metadata:
  name: pi60808-proj1-mariadb
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/pi60808-proj1/mariadb
